INSERT INTO PERSON(FIRSTNAME, LASTNAME, BIRTHDATE) values('Bill', 'Clinton', '1946-08-19');
INSERT INTO PERSON(FIRSTNAME, LASTNAME, BIRTHDATE) values('George', 'W. Bush', '1946-07-06');
INSERT INTO PERSON(FIRSTNAME, LASTNAME, BIRTHDATE) values('Barack', 'Obama', '1961-08-04');
INSERT INTO PERSON(FIRSTNAME, LASTNAME, BIRTHDATE) values('Donald', 'Trump', '1946-06-14');