/****** Object:  Database [CINEMA]    Script Date: 27/03/2019 19:38:59 ******/
CREATE DATABASE [CINEMA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CINE_APP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\CINE_APP.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CINE_APP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\CINE_APP_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CINEMA] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CINEMA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CINEMA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CINEMA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CINEMA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CINEMA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CINEMA] SET ARITHABORT OFF 
GO
ALTER DATABASE [CINEMA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CINEMA] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [CINEMA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CINEMA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CINEMA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CINEMA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CINEMA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CINEMA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CINEMA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CINEMA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CINEMA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CINEMA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CINEMA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CINEMA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CINEMA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CINEMA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CINEMA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CINEMA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CINEMA] SET RECOVERY FULL 
GO
ALTER DATABASE [CINEMA] SET  MULTI_USER 
GO
ALTER DATABASE [CINEMA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CINEMA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CINEMA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CINEMA] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CINEMA', N'ON'
GO
/****** Object:  Table [dbo].[BANNER]    Script Date: 27/03/2019 19:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BANNER](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[date] [datetime2](7) NULL,
	[filename] [varchar](255) NULL,
	[status] [varchar](255) NULL,
	[title] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MOVIE_DETAILS]    Script Date: 27/03/2019 19:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MOVIE_DETAILS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[actors] [varchar](255) NULL,
	[director] [varchar](255) NULL,
	[synopsis] [text] NULL,
	[trailer] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MOVIES]    Script Date: 27/03/2019 19:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MOVIES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[classification] [varchar](255) NULL,
	[duration] [int] NOT NULL,
	[filename] [varchar](255) NULL,
	[releaseDate] [datetime2](7) NULL,
	[status] [varchar](255) NULL,
	[title] [varchar](255) NULL,
	[type] [varchar](255) NULL,
	[detail_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_ragi6whancb4l1qs8pkqrkq1f] UNIQUE NONCLUSTERED 
(
	[detail_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NEWS]    Script Date: 27/03/2019 19:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NEWS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[publicationDate] [datetime2](7) NULL,
	[detail] [text] NULL,
	[status] [varchar](255) NULL,
	[title] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ROLES]    Script Date: 27/03/2019 19:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROLES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_1s6p3xpt8owdb603jky0mo815] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SHOWTIMES]    Script Date: 27/03/2019 19:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SHOWTIMES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[date] [datetime2](7) NULL,
	[price] [float] NOT NULL,
	[room] [varchar](255) NULL,
	[time] [varchar](255) NULL,
	[movie_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 27/03/2019 19:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[USERS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[email] [varchar](255) NULL,
	[name] [varchar](255) NULL,
	[password] [varchar](255) NULL,
	[phone] [varchar](255) NULL,
	[status] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_kby09mn7e5oe95v5ykdm0c0lq] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[USERS_ROLES]    Script Date: 27/03/2019 19:38:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS_ROLES](
	[user_id] [int] NOT NULL,
	[role_id] [int] NOT NULL,
 CONSTRAINT [UKki8x30j3ar7btq9nt2h8kpsmv] UNIQUE NONCLUSTERED 
(
	[user_id] ASC,
	[role_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[MOVIES]  WITH CHECK ADD  CONSTRAINT [FKj6vj1rbic4diyi5388490oqdq] FOREIGN KEY([detail_id])
REFERENCES [dbo].[MOVIE_DETAILS] ([id])
GO
ALTER TABLE [dbo].[MOVIES] CHECK CONSTRAINT [FKj6vj1rbic4diyi5388490oqdq]
GO
ALTER TABLE [dbo].[SHOWTIMES]  WITH CHECK ADD  CONSTRAINT [FKjgtqe2xus31j1c12wytq2110g] FOREIGN KEY([movie_id])
REFERENCES [dbo].[MOVIES] ([id])
GO
ALTER TABLE [dbo].[SHOWTIMES] CHECK CONSTRAINT [FKjgtqe2xus31j1c12wytq2110g]
GO
ALTER TABLE [dbo].[USERS_ROLES]  WITH CHECK ADD  CONSTRAINT [FKnoseerj3xr32i73kjox69kgs1] FOREIGN KEY([user_id])
REFERENCES [dbo].[USERS] ([id])
GO
ALTER TABLE [dbo].[USERS_ROLES] CHECK CONSTRAINT [FKnoseerj3xr32i73kjox69kgs1]
GO
ALTER TABLE [dbo].[USERS_ROLES]  WITH CHECK ADD  CONSTRAINT [FKs9jph45raq0bh9bihmviuubd3] FOREIGN KEY([role_id])
REFERENCES [dbo].[ROLES] ([id])
GO
ALTER TABLE [dbo].[USERS_ROLES] CHECK CONSTRAINT [FKs9jph45raq0bh9bihmviuubd3]
GO
ALTER DATABASE [CINEMA] SET  READ_WRITE 
GO