CREATE TABLE LOGS (
	SORTED	VARCHAR(250)    NOT NULL,
    DATED   VARCHAR(50)	    NOT NULL, --//DATATIME
    LEVEL   VARCHAR(10) 	NOT NULL,
    LOGGER  VARCHAR(100)    NOT NULL,
    MESSAGE VARCHAR(1000)  	NOT NULL
);