CREATE DATABASE POC_HB03_xml_oneToOne_identicalPrimaryKeys;
CREATE DATABASE POC_HB03_xml_oneToOne_unidirectional;
CREATE DATABASE POC_HB03_annotation_oneToOne_identicalPrimaryKeys;
CREATE DATABASE POC_HB03_annotation_oneToOne_unidirectional;
CREATE DATABASE POC_HB03_annotation_oneToOne_unidirectional_table;
CREATE DATABASE POC_HB03_xml_oneToOne_bidirectional;
CREATE DATABASE POC_HB03_annotation_oneToOne_bidirectional;
CREATE DATABASE POC_HB03_annotation_oneToOne_bidirectional_identicalPrimaryKeys;
