/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMethods */

#ifndef _Included_NativeMethods
#define _Included_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMethods
 * Method:    greet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMethods_greet
  (JNIEnv *, jclass);

/*
 * Class:     NativeMethods
 * Method:    sum
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_NativeMethods_sum
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     NativeMethods
 * Method:    reverse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeMethods_reverse
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeMethods
 * Method:    getPrimeNumbers
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_NativeMethods_getPrimeNumbers
  (JNIEnv *, jobject, jint);

/*
 * Class:     NativeMethods
 * Method:    sumAndReverse
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_NativeMethods_sumAndReverse
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     NativeMethods
 * Method:    setInstanceValue
 * Signature: (LResult;I)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_setInstanceValue
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     NativeMethods
 * Method:    setClassValue
 * Signature: (Ljava/lang/Class;D)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_setClassValue
  (JNIEnv *, jobject, jclass, jdouble);

/*
 * Class:     NativeMethods
 * Method:    compute
 * Signature: (LSomeMethods;)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_compute__LSomeMethods_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     NativeMethods
 * Method:    compute
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_compute__Ljava_lang_Class_2
  (JNIEnv *, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
