INSERT INTO PERSON(FIRSTNAME, LASTNAME, BIRTHDATE) values('Bill', 'Clinton', '1945-05-10');
INSERT INTO PERSON(FIRSTNAME, LASTNAME, BIRTHDATE) values('George', 'W. Bush', '1938-06-17');
INSERT INTO PERSON(FIRSTNAME, LASTNAME, BIRTHDATE) values('Barack', 'Obama', '1968-09-02');
INSERT INTO PERSON(FIRSTNAME, LASTNAME, BIRTHDATE) values('Donald', 'Trump', '1935-03-25');


