create table PERSON
  (ID integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) primary key, --//ID integer identity primary key,
  FIRSTNAME varchar(50) NOT NULL,
  LASTNAME varchar(50) NOT NULL,
  BIRTHDATE date null);
