version: '3'
services:
  mysql:
    image: mysql:5.7.28
    #command: --default-authentication-plugin=mysql_native_password
    ports:
        - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=POC_JOBS
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - frontend-network
      - backend-network

volumes:
  mysql_data:

networks:
  frontend-network:
  backend-network:
